### PR TITLE
Adding CI build pipeline with Github Action

### PR DESCRIPTION
**Pull request by chris24walsh**

### CODE REVIEW

**Comment by chris24walsh** [comment]
Sorry about the mess :) I pushed the first few commits directly to master, then decided I should open a PR instead to keep track of this new CI/CD work.

**Comment by matthiku** [comment]
No worries. Go ahead and merge.
Btw.,the reason why I don't use Docker myself is that it is in conflict with my VirtualBox and also because I use Laravel, which allows me to use https and a customer URL for local testing.

**Comment by chris24walsh** [comment]
@matthiku I've encountered installation dependency issues before, and again now with your latest commits. So I'd like to introduce this CI/CD pipeline so we can be on the same page, and identify immediately any more dependency issues. With regard to your reasons against Docker, I'm not sure I understand. Wouldn't it be straightforward to do that also with containers?

**Comment by chris24walsh** [comment]
Btw, let's not merge this PR until it is at least passing the github action that it is introducing! :)

**Comment by matthiku** [comment]
Probably. It's just easier for me but then I don't know enough about Docker/containers.
Care of having a quick video call e.g. on Jitsi.org to discuss this?

**Comment by chris24walsh** [comment]
Yeah, that would be great! How about 17:10? Also, I'm not stuck on Docker, but I do think it would be best to nail down the build in a pipeline like this, since it makes it much easier to colaborate.

**Comment by matthiku** [comment]
I'll send an invite for that meeting. Is your gmail address still working? (chris24....)

**Comment by chris24walsh** [comment]
Yep, I have the details from your previous mail on Wednesday. Sorry for not replying yet :)

**Pull request closed without merging**
