### PR TITLE
Integrate ci workflow to master

### PR DESCRIPTION
**Pull request by chris24walsh**
Time to finally merge the CI workflow into the latest master.

### CODE REVIEW

**Comment by chris24walsh** [comment]
Ok, great! Now we know that the added CI pipeline is working with latest code in master :) And now, going forward, you have build tests on any pushes directly to master, or any pull requests.
I suggest protecting the master branch to prevent direct pushing, and relying on opening new feature branches and pull requests to master for continuing development. This is best practice when dealing with an open source project with other collaborators and users, to prevent breaking changes downstream. You don't have to use Docker yourself locally or in your production deployment, but I would also highly recommend it :) Let's have a call sometime this week and discuss further.

**Comment by matthiku** [comment]
@chris24walsh 
This all goes a little bit (understatement!) over my head ... ;) I have never worked in this kind of environment before. Basically, I only used GitHub as my very convenient project repository ...
But yes, please arrange for a call, I'm available any time more or less and at short notice. I'm not planning to go anywhere anytime soon! :D

**Comment by chris24walsh** [comment]
Thanks for the encouragement @matthiku! I am delighted to be able to add value to the project, this is basically the area I work in - [DevOps](https://en.wikipedia.org/wiki/DevOps). I don't have much software development experience though, and none on a community project, so I am learning a lot from you and being a part of this project :)
From a DevOps perspective, it's not about the particular tools we use, but adopting better processes that make work better for the people involved. Some of the newer tools really help though!
I could really use your experience though, for extending the functionality of the Dockerfile. I need to add a mail server to the docker container so that the email password reset works out-of-the-box. Can you help me with setting up an appropriate mail server on Ubuntu 16.04? Also, I opened a new PR to update the Dockerfile to use ubuntu-latest - there are currently incompatibility issues.

**Comment by matthiku** [comment]
Let me know when you want to have another Zoom session and we can discuss all of this ....

**Pull request merged**
